name: rotm
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  smooth_page_indicator: ^1.1.0
  lottie: ^2.7.0
  flutter_native_splash: ^2.3.9
  google_fonts: ^6.1.0
  http: ^1.1.2
  awesome_snackbar_content: ^0.1.3
  curved_navigation_bar: ^1.0.3
  percent_indicator: ^4.2.3
  radar_chart: ^2.1.0
  fl_chart: ^0.66.0
  animations: ^2.0.11
  syncfusion_flutter_charts: ^24.1.45+2
  syncfusion_flutter_gauges: ^24.1.45
  gauge_indicator: ^0.4.3
  email_validator: ^2.1.17
  regexed_validator: ^2.0.0+1
  flutter_heatmap_calendar: ^1.0.5
  qr_flutter: ^4.1.0
  animate_do: ^3.3.3
  speech_to_text: ^6.6.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/images/logo.png"

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/
    - lib/assets/others/
    - lib/assets/animated/
